theme: jekyll-theme-minimal
title: OBO Dashboard
description: > # this means to ignore newlines until "show_excerpts:"
  The OBO-Dashboard automatically checks ontologies for adherence to OBO Foundry principles.
show_excerpts: false # set to true to show excerpts on the homepage
